# Pytorch introduction and some common functions

### What is pytorch?
- PyTorch is a deep learning framework and a scientific computing package that uses the power of graphics processing units.
- Pythonic in nature, we can smoothly integrate it with python data science stack.
- PyTorch provides an excellent platform which offers dynamic computational graphs, thus we can change them during runtime.

### Functions 
- rand function
- view and slicing function
- maths function
- cat function
- linspace function

In [2]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.rand

rand function will return a tensor with random numbers it requires size as the input, 
we have to specify the size

In [3]:
# Example 1 - creating a two dimensional tensor by providing the size of the tensor
torch.rand(2,2)

tensor([[0.7515, 0.2303],
        [0.0620, 0.3073]])

Explanation about example
> creating one dimensional and three dimensional tensor

In [4]:
# Example 2 - one dimension tensor and three dimensional
x = torch.rand(2)
y = torch.rand(4,5,2)
print(x)
print(y)

tensor([0.2028, 0.5011])
tensor([[[0.8217, 0.2133],
         [0.9548, 0.5199],
         [0.5160, 0.2496],
         [0.3304, 0.0572],
         [0.7620, 0.1137]],

        [[0.1674, 0.7317],
         [0.8884, 0.4211],
         [0.2321, 0.5860],
         [0.1328, 0.3146],
         [0.5628, 0.1659]],

        [[0.8175, 0.2154],
         [0.0333, 0.5034],
         [0.0608, 0.9238],
         [0.8084, 0.3204],
         [0.6408, 0.6321]],

        [[0.8172, 0.1665],
         [0.7147, 0.1513],
         [0.0866, 0.1007],
         [0.0949, 0.7260],
         [0.6869, 0.9485]]])


Explanation about example
> if we does'nt provide the size and shape value, than it will break because it requires tensor shape value

In [5]:
# Example 3 - 
torch.rand()

TypeError: rand() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


Explanation about rand function

we can use rand function when we want to test something and it requires data but we dont have any data,so in that case we can use rand function for generating the random data.

## Function 2 - torch.view and tensor.reshape

view function requires when we have to reshape the structure of a tensor

In [6]:
# generating the random data using rand function
z = torch.rand(4,4) #four rows and four columns
print(z)
z.view(2,8) #two rows and 8 columns


tensor([[0.5457, 0.2317, 0.7707, 0.4411],
        [0.3650, 0.0557, 0.8655, 0.4967],
        [0.5487, 0.6117, 0.3907, 0.2767],
        [0.6043, 0.5569, 0.7527, 0.4382]])


tensor([[0.5457, 0.2317, 0.7707, 0.4411, 0.3650, 0.0557, 0.8655, 0.4967],
        [0.5487, 0.6117, 0.3907, 0.2767, 0.6043, 0.5569, 0.7527, 0.4382]])

### converting a two dimensional tensor into four dimensional tensor using view function

In [7]:
print(z.view(2,2,2,2)) # four dimensional 
print(torch.reshape(z,(1,16)))

tensor([[[[0.5457, 0.2317],
          [0.7707, 0.4411]],

         [[0.3650, 0.0557],
          [0.8655, 0.4967]]],


        [[[0.5487, 0.6117],
          [0.3907, 0.2767]],

         [[0.6043, 0.5569],
          [0.7527, 0.4382]]]])
tensor([[0.5457, 0.2317, 0.7707, 0.4411, 0.3650, 0.0557, 0.8655, 0.4967, 0.5487,
         0.6117, 0.3907, 0.2767, 0.6043, 0.5569, 0.7527, 0.4382]])


if we don't provider correct rows and column values than it will break.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
z.view(2,3)

RuntimeError: shape '[2, 3]' is invalid for input of size 16

Explanation about example

we can use view and reshape function, where the requirement is like same data points but diffrent structure.

## Function 3 - maths function like torch.add, torch.mul, add_, mul_

torch.add for adding two or tensor element wise or multiply the values using torch.mul function

In [9]:
# Example 1 - working
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a + b)             #from both the operation we will get the same result
print(torch.add(a,b))
print(a.add_(b))  #this will add the b value in a with inplace operation

tensor([[0.3113, 0.5481],
        [1.4355, 1.0435]])
tensor([[0.3113, 0.5481],
        [1.4355, 1.0435]])
tensor([[0.3113, 0.5481],
        [1.4355, 1.0435]])


### multiplication function

In [10]:
# Example 2 - working
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a * b)             #from both the operation we will get the same result
print(torch.mul(a,b))
print(a.mul_(b))  #this will add the b value in a with inplace operation

tensor([[0.4113, 0.5747],
        [0.1571, 0.4338]])
tensor([[0.4113, 0.5747],
        [0.1571, 0.4338]])
tensor([[0.4113, 0.5747],
        [0.1571, 0.4338]])


### for addition or for some other functions, the tensors size should be same otherwise it will throw error

In [11]:

a = torch.rand(2,3)
b = torch.rand(2,2)
print(a + b)             #from both the operation we will get the same result
print(torch.add(a,b))
print(a.add_(b))  #this will add the b value in a with inplace operation

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

Explanation about example

in above cases i have just explore some basic maths functions


## Function 4 - torch.cat

- torch.cat function concatenates the given sequence of tensors in the given dimensions
- it takes two input, first is tensor and second is axis(concatenates along the column or row)

In [12]:
# Example 1 - working
d = torch.rand(2,4)
torch.cat((d,d),0)

tensor([[0.2632, 0.8819, 0.9912, 0.0286],
        [0.9163, 0.0257, 0.1483, 0.6376],
        [0.2632, 0.8819, 0.9912, 0.0286],
        [0.9163, 0.0257, 0.1483, 0.6376]])

concatenates along the column

In [13]:
# Example 2 - working
torch.cat((d,d,d),1)

tensor([[0.2632, 0.8819, 0.9912, 0.0286, 0.2632, 0.8819, 0.9912, 0.0286, 0.2632,
         0.8819, 0.9912, 0.0286],
        [0.9163, 0.0257, 0.1483, 0.6376, 0.9163, 0.0257, 0.1483, 0.6376, 0.9163,
         0.0257, 0.1483, 0.6376]])

In this example i provide the wrong axis and that will lead to error.
It means, we should provide the axis value after cakculating the shape and size of the tensor.

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
torch.cat((d,d,d),2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Explanation about example

Concatenates function uses, where we want to merge two tensors according to axis.

## Function 5 - torch.linspace

this function will return a one dimensional tensor of steps equally spaced points between start and end values. if dont provide steps than it will take it 100 as default.

start is 1, end is 10, steps is 5, so it will generate 5 values between 1 to 10 and that will be equally spaced.

In [15]:
# Example 1 - working
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

start is 5, end is 10, steps is 5, so it will generate 5 values between 5 to 10 and that will be equally spaced

In [16]:
# Example 2 - working
torch.linspace(5.0,10,5)

tensor([ 5.0000,  6.2500,  7.5000,  8.7500, 10.0000])

the steps value should be integer else it will throw error

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(5,10,5.0)

TypeError: linspace(): argument 'steps' (position 3) must be int, not float

Explanation about example

requirement of this function is when we required data that is equally spaced and randomaly generated.

## Conclusion

In this notebook i have provided some basic and common functions of pytorch

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [18]:
!pip install jovian --upgrade --quiet

In [19]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
